### ISSUE TITLE
Multi-threading RX usage

### ISSUE THREAD

**Issue by pchaseh** [HeroicKatora/xdpilone#2]
I'm attempting to use this crate such that each RX queue gets its own socket, with said socket running in a separate thread, however it appears as if neither `Umem` nor `UmemChunk` types can be passed to threads because they use this type for some fields:
```
`NonNull<[u8]>` cannot be sent between threads safely
```
Would it be possible to either provide an example for this (maybe there's a better way of doing it, but I don't see how with this constraint) or consider reworking it such that this is supported? My code:

```rust
    // Allocate one xsk per queue, with UMEM being shared between them
    let mut iface = ifinfo(opt.iface.clone(), Some(0)).unwrap();
    let mut sock = Some(Socket::with_shared(&iface, &umem).unwrap());

    let handles = (0..opt.num_queues).map(|queue_id| {
        iface.set_queue(queue_id);
        let sock = sock.take().unwrap_or_else(|| Socket::new(&iface).unwrap());

        // Fill queue/completion queue
        let mut fq_cq: xdpilone::DeviceQueue = umem.fq_cq(&sock).unwrap();

        // RX + TX queues
        let rxtx = umem.rx_tx(&sock, &cfg).unwrap();
        let mut rx: xdpilone::RingRx = rxtx.map_rx().unwrap();

        umem.bind(&rxtx).unwrap();

        socks.set(queue_id, rx.as_raw_fd(), 0).unwrap();

        let frame = umem.frame(BufIdx(0)).unwrap();

        std::thread::spawn(move || {
            thread_run(
                &XskContext{
                    queue_id: queue_id,
                    xsk: sock,
                    // Compilation error if either `Umem` or `UmemChunk` gets passed to a thread
                    umem: umem,
                    fc_queue: fq_cq,
                    rx_queue: rx,
                }
            )
        })
    }).collect::<Vec<_>>();
```

**Comment by HeroicKatora** [comment]
It should definitely be possible to make `impl Sync for Umem`, and probably also `impl Send for Umem`. I wouldn't do it for `UmemChunk` though. This type is really meant to be an equivalent of a raw pointer, which the standard library doesn't mark with those traits on purpose. If your use entails sending those buffers to a separate thread, the struct is trivial to destructure and has no invariants nor any other use in interfaces that would require its object identity to be preserved. Just construct it on use.

Pull request with a more thoroughly thought-out `Safety` comment regarding each of the `Sync`/`Send` implementations for `Umem` would be welcome to publish as `1.0.4`.

**Comment by HeroicKatora** [comment]
I've decided not to keep somewhat vague requests open as issues. Please use discussions and pull requests, or contract work for support.
